apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
namespace: default
# https://gap.gjensidige.io/docs/guides/ci-automation-with-kustomize
images:
- name: backend
  newName: 796618404628.dkr.ecr.eu-central-1.amazonaws.com/demo-k8s-ecr-repository
  newTag: "17"
